#!/bin/sh

# inve
#
# usage: inve [COMMAND [ARGS]]
#
# For use with Ian Bicking's virtualenv tool. Attempts to find the root of
# a virtual environment. Then, executes COMMAND with ARGS in the context of
# the activated environment. If no COMMAND is given, activate defaults to a
# subshell.

# First, locate the root of the current virtualenv
while [ "$PWD" != "/" ]; do
    # Stop here if this the root of a virtualenv

    if [ \
        -f bin/python \
        -a -e lib/python*/site.py ]
    then
        break
    fi
    cd ..
done
if [ "$PWD" = "/" ]; then
    echo "Could not activate: no virtual environment found." >&2
    exit 1
fi

# Activate
export VIRTUAL_ENV="$PWD"
unset PYTHON_HOME
export PATH="$VIRTUAL_ENV/bin:$PATH"
exec "${@:-$SHELL}"
