#!/usr/bin/env bash

set -e

# Settings that tweak macOS to make it do what I want and keep configuration common across various devices.
# 
# Again, configuration management for the win.

echo 'Configuring macOS. Hold on to something!'

osascript -e 'tell application "System Preferences" to quit'

# Dock options
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock largesize -float 75
defaults write com.apple.dock magnification -bool true
defaults write com.apple.dock show-recents -bool false
defaults write com.apple.dock tilesize -float 35
defaults write com.apple.dock showhidden -bool true

# Always use extended save dialogue, damnit.
defaults write NSGLobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGLobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Allow text selection in quicklook

defaults write com.apple.finder QLEnableTextSelection -bool true

# Disable full stop on double-space
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

echo 'Restarting...'
killall Finder
killall Dock
